name: optimized_cached_image
description: A library for loading images from network, resizing as per container size and caching while being memory sensitive.
version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_image_compress: ^2.3.0
  uuid: ^4.5.0
  http: ^1.2.2
  path_provider: ^2.1.4
  path: ^1.9.0
  pedantic: ^1.11.0
  sprintf: ^7.0.0
  octo_image: ^2.1.0
  image: ^4.2.0
  file: ^7.0.0
dev_dependencies:
  test: ^1.16.8
  flutter_lints: ^4.0.0
